config/routes.rb
Website::Application.routes.draw do

  resources :blogposts

  get "pages/home"
  get "pages/contact"
  match '/contact', :to => 'pages#contact'

  root :to => "pages#home"

end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
  attr_accessible :title, :content
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController

  def index
    @blogposts = Blogpost.all
  end

  def new
    @blogpost = Blogpost.new
  end

  def create
    @blogpost = Blogpost.new(params[:blogpost])
    @blogpost.save
  end

  def show
    @blogpost = Blogpost.find(params[:id])
  end

  def edit
    @blogpost = Blogpost.find(params[:id])
  end

  def update
    @blogpost = Blogpost.find(params[:id])
    if @blogpost.update_attributes(params[:blogpost])
      flash[:success] = "Profile updated!"
      redirect_to @blogpost
    else
      render 'edit'
    end
  end

  def destroy
    Blogpost.find(params[:id]).destroy
    flash[:success] = "User destroyed!"
    redirect_to blogpost_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogposts/create.html.haml
%body
  = stylesheet_link_tag "blogposts", :media => "all"
  .body-wrap
    .blogpost
      .title
        = @blogpost.title
      .content
        = @blogpost.content
      .time
        = @blogpost.created_at

app/views/blogposts/edit.html.haml
%body
  = stylesheet_link_tag "blogposts", :media => "all"
  .body-wrap
    = form_for(@blogpost) do |f|
      .field
        = f.label :title
        <br>
        = f.text_field :title
      .field
        = f.label :content
        <br>
        = f.text_area :content
      .actions
        = f.submit "Update"

app/views/blogposts/index.html.haml
%body
  = stylesheet_link_tag "blogposts", :media => "all"
  .body-wrap
    .blogpost
      .add-new
        = link_to "New Post", new_blogpost_path
      - @blogposts.each do |post|
        .title
          = link_to post.title, post
        .content
          = truncate(post.content, :length => 500, :separator => " ")
        .time
          = post.created_at
        <br>

app/views/blogposts/new.html.haml
%body
  = stylesheet_link_tag "blogposts", :media => "all"
  .body-wrap
    = form_for(@blogpost) do |f|
      .field
        = f.label :title
        <br>
        = f.text_field :title
      .field
        = f.label :content
        <br>
        = f.text_area :content
      .actions
        = f.submit "Post"

app/views/blogposts/show.html.haml
%body
  = stylesheet_link_tag "blogposts", :media => "all"
  .body-wrap
    .blogpost
      .title
        = @blogpost.title
      .content
        = @blogpost.content
      .delete
        = link_to "Delete", @blogpost, :method => :delete, :confirm => "Are you sure?"
      .edit
        = link_to "Edit", edit_blogpost_path(@blogpost)
        ||
      .time
        = @blogpost.created_at
        ||

app/views/layouts/application.html.haml
%html
  %header
    .logo
      = link_to "BRIAN" , "/"
    .nav
      %ul
        %li
          = link_to "blog", blogposts_path
        %li
          = link_to "projects", "#"
        %li
          = link_to "photos", "#"
        %li
          = link_to "contact", contact_path
  %title
    Brian Wu
  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body
  = yield

app/views/pages/contact.html.haml
%body
  = stylesheet_link_tag "pages", :media => "all"
  .body-wrap
    .content
      Contact

app/views/pages/home.html.haml
%body
  = stylesheet_link_tag "pages", :media => "all"
  .body-wrap
    .content
      Hello,<br>
      I'm Brian